---
- name: deploy as3 declaration
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
    uri_method: POST


  vars_files:
    - ../creds/big_creds.yaml


  tasks:
  
  - name: rest call to big-ip
    uri:
      url: https://18.134.162.22/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','./as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_output

  - name: debug as3 output
    debug:
      msg: "my as3 output {{ as3_output }}"




















...